### ISSUE TITLE
Question about the installation process on Intel system

### ISSUE THREAD

**Issue by HB-fga** [T-Troll/alienfx-tools#349]
I dont't know if opening an issue is the best way to ask this, but I found no other method of contact so here we go.

I'm using your software on my Dell G15 i5-12500H + RTX 3050. I downloaded release 8.2.7, ran alienfan-gui, ran check max boost, created my fan curve and it seems to be working fine, however I just recently read your installation section on the readme and it says:

- `In case you are using .zip archive and have Intel system, copy files from DPTF folder to <Windows folder>\System32\drivers\DriverData\Intel\DPTF\dv\`

But inside my "Intel" folder there is no "DPTF" folder, theres only a "IPF" folder and inside it theres a folder called "dv".

Why is this process required? And should I paste the files inside "<Windows folder>\System32\drivers\DriverData\Intel\IPF\dv\" instead?

Since I already opened and Issue I would also like to ask what exactly do the `CPU Mode AC` and `Battery` Drop down menus do on alienfan-gui?

**Comment by T-Troll** [comment]
> I dont't know if opening an issue is the best way to ask this, but I found no other method of contact so here we go.

I have a Discord server listed into project readme. Also Alienware community at Reddit.

> Why is this process required? And should I paste the files inside "\System32\drivers\DriverData\Intel\IPF\dv" instead?

At Intel, you have "ESIF" sensors into the list. Doing this can provide its real names from BIOS (Intel not expose it to WMI for unknown reason). Since you have 12th gen CPU, patch may vary, so try this one, but you need to change one registry settings after to re-check names.

> Since I already opened and Issue I would also like to ask what exactly do the CPU Mode AC and Battery Drop down menus do on alienfan-gui?

These settings control hidden setting of the Windows Power Plan, defining CPU acceleration/deceleration policy,
It's make a good boost for AMD systems, but not so important for Intel ones.

**Comment by HB-fga** [comment]
Thank you for the answers, I'm closing the issue, any other question that I have I'll ask on the Discord or Reddit communities
